// cSpell:ignore latoRegular, latoBold

export const MAX_WIDTH = '1200px'
export const BASE_SIZE = '1rem'
export const XS_SIZE = parseInt(BASE_SIZE) * 0.5 + 'rem'
export const SM_SIZE = parseInt(BASE_SIZE) * 1 + 'rem'
export const MD_SIZE = parseInt(BASE_SIZE) * 1.5 + 'rem'
export const LG_SIZE = parseInt(BASE_SIZE) * 2 + 'rem'
export const XL_SIZE = parseInt(BASE_SIZE) * 3 + 'rem'
export const XXL_SIZE = parseInt(BASE_SIZE) * 4 + 'rem'
export const PRIMARY_COLOR = '#4a82bc'
export const SECONDARY_COLOR = '#aacbef'
export const THIRD_COLOR = '#ffffff'
export const PRIMARY_DARK_COLOR = '#f4f4f4'
export const SECONDARY_DARK_COLOR = '#7a7e82'
export const THIRD_DARK_COLOR = '#201125'
export const ERROR_COLOR = '#d04840'
export const PRIMARY_FONT = 'latoRegular'
export const SECONDARY_FONT = 'latoBold'
export const BORDER_RADIUS_SIZE = parseInt(BASE_SIZE) * 0.5 + 'rem'
export const BORDER_RADIUS_SIZE_CIRCLE = parseInt(BASE_SIZE) * 5 + 'rem'
export const THIN_BORDER = parseInt(BASE_SIZE) * 0.2 + 'rem' + ' solid'
export const DELAY = '0.2s'
export const LONG_DELAY = '0.4s ease-in-out'
export const BREAKPOINT_XS_MIN = '0px'
export const BREAKPOINT_XS_MAX = '576px'
export const BREAKPOINT_SM_MIN = parseInt(BREAKPOINT_XS_MAX) + 1 + 'px' // 577
export const BREAKPOINT_SM_MAX = '768px'
export const BREAKPOINT_MD_MIN = parseInt(BREAKPOINT_SM_MAX) + 1 + 'px' // 769
export const BREAKPOINT_MD_MAX = '992px'
export const BREAKPOINT_LG_MIN = parseInt(BREAKPOINT_MD_MAX) + 1 + 'px' // 993
export const BREAKPOINT_LG_MAX = '1200px'
export const BREAKPOINT_XL_MIN = parseInt(BREAKPOINT_LG_MAX) + 1 + 'px' // 1201
export const BREAKPOINT_XL_MAX = '1400px'
export const BREAKPOINT_XXL_MIN = parseInt(BREAKPOINT_XL_MAX) + 1 + 'px' // 1401
